blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs_view, name='all_blogs'),
    path('<int:blog_id>/', views.blog_detail_view, name='blog_detail'),
]

personal_portofolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portofolio.urls')),
    path('blog/', include('blog.urls')),

]

portofolio/urls.py
from django.urls import path

from . import views

app_name = 'portofolio'

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('test/', views.test_page_view, name='test'),
]

blog/models.py
from datetime import datetime

from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField(default=datetime.now())
    content = models.TextField()

    def __str__(self):
        return self.title

portofolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='static/proj_images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs_view(request):
    blogs = Blog.objects.all()
    # blogs = Blog.objects.order_by('-date')
    latest_blogs = Blog.objects.order_by('-date')[:4]
    blog_count = Blog.objects.count()
    # blogs = Blog.objects.filter(date="2021-11-23")
    context = {
        'blogs': blogs,
        'latest_blogs': latest_blogs,
        'blog_count': blog_count
    }
    return render(request, 'blog/all_blogs.html', context)


def blog_detail_view(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    context = {
        'blog': blog
    }
    return render(request, 'blog/blog_detail.html', context)

portofolio/views.py
from django.shortcuts import render
from .models import Project


def home_page_view(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'portofolio/homepage.html', context)


def test_page_view(request):
    return render(request, 'portofolio/testing.html', {})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="html_class">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'portofolio/custom.css' %}">

    <link rel="shortcut icon" type="image/png" href="{% static 'logo_map.png' %}"/>
    <style>
        {% block style %}
        {% endblock %}
    </style>

    <title>{% block title %} power_to_the_base {% endblock %}</title>

</head>
<body>

<nav id="topNav" class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'portofolio:home' %}">
            <img src="{% static 'logo_map.png' %}" width="30" height="30" class="d-inline-block align-top"
                 alt="Mircea's Logo">
            <span>Mircea Apopei</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portofolio:test' %}">Test Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/MirceaAp" target="_blank">GitHub</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.linkedin.com/in/mircea-apopei/" target="_blank">LinkedIn</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% static 'portofolio/Mircea_CV.pdf' %}" target="_blank">Resume</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}This will be my body!{% endblock %}
</div>

{#{% block footer %}#}
{#    <h3>n-am ce footer</h3>#}
{#{% endblock %}#}
<
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

templates/blog/all_blogs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Blog{% endblock %}

{% block body %}

{#    <h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>#}

    <h3 class="text-center mb-10">These are the blogs so far:</h3>

    {% for blog in blogs %}
        <div class="row justify-content-center my-3">
            <div class="col-md-10">
                <a href="{% url 'blog:blog_detail' blog.id %}"><h4>{{ blog.title }}</h4></a>
                <h5 class="text-muted">Posted on {{ blog.date|date:'M d Y' }}</h5>
                {# https://docs.djangoproject.com/en/3.2/ref/templates/builtins/ #}
                <p>{{ blog.content|truncatechars:50 }}</p>
            </div>
        </div>
    {% endfor %}



{% endblock %}

templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Detail{% endblock %}

{% block body %}

    <div class="container text-center">
        <h1 class="alert alert-success">{{ blog.title }}</h1>
        <h1>Date: {{ blog.date|date:'M d Y' }}</h1>
        <h5>As is: {{ blog.content}}</h5>
        <br>
        <h5>With html tags applied: {{ blog.content|safe}}</h5>
        <br>
        <h5>With html tags removed: {{ blog.content|striptags}}</h5>
        <br>
{#        <div>#}
{#            {% for blog in blogs %}#}
{#                <h2>Blog Title: {{ blog.title }}</h2>#}
{#                <h3>This blog was created on the {{ blog.date }}</h3>#}
{#                <p>blog description: {{ blog.description }}</p>#}
{#                <p>blog content: {{ blog.content }}</p>#}
{#            {% endfor %}#}
{#        </div>#}

    </div>
{% endblock %}

templates/portofolio/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MirceaAp Portfolio{% endblock %}

{% block body %}

    <div class="row justify-content-center my-3">
        <div class="col-5">
            <img src="{% static 'portofolio/Mircea_batranul.jpg' %}" class="img-fluid rounded mx-auto d-block"
                 alt="Sorry, no pic available for you today...">
        </div>
    </div>

    <div class="row justify-content-center mb-3">
        <div class="col-md-9 text-center">
            <h1 id="hometext" class="font-weight-bold">Hi! My name is Mircea!!! 😊</h1>
        </div>
    </div>

    <h2 class="mt-5">Portfolio</h2>
    <hr>
    <div class="row">
        {% for project in projects %}
            <div class="col-lg-4 col-md-6">

                {% if project.url %}
                    <a href="{{ project.url }}" target="_blank">
                        <img src="{{ project.image.url }}" class="img-fluid mb-2">
                    </a>
                {% else %}

                    <img src="{{ project.image.url }}" class="img-fluid mb-2">
                {% endif %}
                <h3>{{ project.title }}</h3>
                <p>{{ project.description }}</p>

            </div>
        {% endfor %}
    </div>


{% endblock %}

templates/portofolio/testing.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    [class*='col'] {
    padding: 1rem;
    background-color: aqua;
    border: 2px solid #fff;
    color: crimson;
    }

    [class*='row'] {
    padding: 1rem;
    background-color: blueviolet;
    border: 2px solid orangered;
    color: black;
    }
{% endblock %}
{% block title %}Test Page{% endblock %}



{% block body %}
    <div class="py-5">
{#        <div class="container text-center">#}
{#            <a href="{% url 'portofolio:home' %}">Home</a>#}
{#        </div>#}
        <h1 class="my-5 text-center">let's test!</h1>
        <div>
            <h2 class="text-center"> Exemplu 1: container simplu cu 1 rand cu 3 coloane si 1 rand cu 2 coloane</h2>
            <div class="container">
                <div class="row">
                    <div class="col">1</div>
                    <div class="col">2</div>
                    <div class="col">3</div>
                </div>
                <div class="row">
                    <div class="col-lg">A</div>
                    <div class="col-md">B</div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div>
            <h2 class="text-center"> Exemplu 2: container fluid cu 1 rand cu 3 coloane si 1 rand cu 2 coloane</h2>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm">1</div>
                    <div class="col-sm">2</div>
                    <div class="col-sm">3</div>
                </div>
                <div class="row">
                    <div class="col-md">A</div>
                    <div class="col-md">B</div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div>
            <h2 class="text-center"> Exemplu 3: container simplu cu 1 rand cu 1 coloana si 1 sidebar</h2>
            <div class="container">
                <div class="row">
                    <div class="col-8">1 coloana</div>
                    <div class="col-4">1 sidebar</div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div>
            <h2 class="text-center"> Exemplu 4: container fluid cu 2 randuri cu cate 1 coloana si 1 sidebar comun</h2>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="row">Marcela</div>
                        <div class="row">
                            <div class="col-sm">Vampiru 1</div>
                            <div class="col-sm">Vampiru 2</div>
                        </div>
                    </div>
                    <div class="col-sm-4">1 sidebar</div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div>
            <h2 class="text-center"> Exemplu 5: container simplu cu 1 rand cu 12 coloane care se aliniaza cate 12, sau
                cate 6 sau cate 4 sau cate 3 sau cate 2 sau cate 1 in fctie de dimensiunea lor</h2>
            <div class="container">
                <div class="row">
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                    <div class="col-xxl-1 col-xl-2 col-lg-3 col-lg-4 col-sm-6 col-xs-12">Lorem ipsum dolor sit amet,
                        consectetur adipiscing elit. In gravida condimentum diam.
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}